"""Create application table

Revision ID: de1a7955e059
Revises: 
Create Date: 2025-04-19 16:35:27.085626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de1a7955e059'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=127), nullable=False),
    sa.Column('password', sa.String(length=127), nullable=False),
    sa.Column('account_type', sa.Enum('ADMIN', 'USER', name='accounttype'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=127), nullable=False),
    sa.Column('last_name', sa.String(length=127), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=127), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('degree', sa.String(length=127), nullable=False),
    sa.Column('field_of_study', sa.String(length=127), nullable=False),
    sa.Column('institution', sa.String(length=127), nullable=False),
    sa.Column('cgpa', sa.Float(), nullable=False),
    sa.Column('transcript_filename', sa.String(length=255), nullable=False),
    sa.Column('id_proof_filename', sa.String(length=255), nullable=False),
    sa.Column('application_status', sa.String(length=63), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application')
    op.drop_table('user')
    # ### end Alembic commands ###
